[tox]
envlist = py314, lint
skipsdist = True

[testenv]
deps =
    -r{toxinidir}/backend/requirements.txt
    pytest
    httpx
setenv =
    PYTHONPATH = {toxinidir}/backend
commands =
    pytest {toxinidir}/backend/app/tests

[testenv:lint]
deps = ruff
commands =
    ruff check {toxinidir}/backend/app
